#pragma config(Sensor, dgtl1,  exampleEncoderName, sensorQuadEncoder)
#pragma config(Motor,  port3,           left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           left2,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           left3,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           right2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           right3,        tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//main include for 72832Lib
#include "72832Lib.h"

void leftFunc(int power){  //send a condition it will set the right drive equal to that condition
	motor[left1] = power;
	motor[left2] = power;
	motor[left3] = power;
}

void rightFunc(int power){  //send a condition it will set the right drive equal to that condition
	motor[right1] = power;
	motor[right2] = power;
	motor[right3] = power;
}

void pidCtrl(int reqDist, int leftTurn = 0, int unitType = 0, clicksPer360DegreeTurn = 1440){//this variable will need to be changed everytime you change your drive and be accurate to the click

	int pidDist;  //this value will eventually be used in the error condition

	//unit type for pid sensor selection. default is clicks
	if( unitType == 1 ){   //this unit type is inches

		pidDist = reqDist * /*degrees / Wheel Circumference*/ (360/(4*3.141529)) ;

	}else if(unitType == 2){//this unit type is feet

		pidDist = reqDist * /*(degrees / Wheel Circumference) * 12*/ (4320/(4*3.141529));

	}else if(unitType == 3){ //this value is tiles (2 feet)

		pidDist = reqDist * /*(degrees / Wheel Circumference) * 24*/ (8640/(4*3.141529));

	}else if(unitType == -1){

		pidDist = reqDist * (
			clicksPer360DegreeTurn / 360);//this variable will need to be changed everytime you change your drive and be accurate to the click

	}else if(unitType == 0){ //this unit type is, by default, clicks

		pidDist = reqDist;

	}

	PID pidExampleStruct;

	PIDInit(&pidExampleStruct, 0.6, 0.01, 0.3);

	// Loop through many times so we can graph
	//  the PID loop
	for(int i = 0; i < 2000; i++){
		int sensorCurrentValue = SensorValue[
			exampleEncoderName /*change this value to your main encoder name*/];

		// This calculates how far off we are from the true value
		//  The PID will return a response that will hopefully minimize this error over time
		float pidResult = PIDCompute( &pidExampleStruct, pidDist - sensorCurrentValue );

		if( leftTurn == 1 ){  //if you change leftTurn = true then it will turn left or right(based on if you send a positive or negative value for reqDist)
			leftFunc(  pidResult * -1 );  //see void leftFunc
			rightFunc( pidResult * 1 ); //see void rightFunc
		}else if( leftTurn == 0 ){  //by default it will go forward or backward(based on if you send a positive or negative value for reqDist)
			leftFunc(  pidResult * 1 );  //see void leftFunc
			rightFunc( pidResult * 1 ); //see void rightFunc
		}

		wait1Msec( abs( reqDist * ( 2000 / 360 ) ) ); //if your reqDist = 360 then it will delay to one second. This can be adjusted but only for advanced users.

	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton(){
    // Set bStopTasksBetweenModes to false if you want to keep user created tasks
    // running between Autonomous and Driver controlled modes. You will need to
    // manage all user created tasks if set to false.
    bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition start
	// Example: clearing encoders, setting servo positions, ...
	SensorValue[exampleEncoderName]=0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
// ..........................................................................
// Insert user code here.
// ..........................................................................

	pidCtrl(360);       //this will run the wheels forward one revolution (assuming the P, I, and D variables work well with your drive)

	pidCtrl(12, 0, 1);  //this will run the wheels 12 inches using the unitType inches

	pidCtrl(1, 0, 2);   //this will also run the wheels 12 inches using the unitType feet

	pidCtrl(.5, 0, 3);  //this will also run the wheels 12 inches using the unitType tiles

	pidCtrl(90, 1, -1); //this will rotate the drive 90 degrees left (for this to work you will need to change a variable)

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol(){
  // User control code here, inside the loop

  while (true){
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
